---
# tasks file for roles/ddns_updater
- name: Create the data directory on workers
  ansible.builtin.file:
    path: "{{ ddns_updater_data_directory }}"
    state: directory
    mode: '0755'
  delegate_to: "{{ item }}"
  with_items: "{{ groups['workers'] }}"
  run_once: true

- name: Create directory for custom values files
  ansible.builtin.file:
    path: "{{ ddns_updater_template_directory }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Find value files in template directory
  ansible.builtin.find:
    paths: "{{ role_path }}/templates"
    patterns: "*.yaml.j2"
  register: value_files
  delegate_to: localhost

- name: Render custom values files locally
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ ddns_updater_template_directory }}/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
    mode: '0644'
  with_items: "{{ value_files.files }}"
  delegate_to: localhost

- name: Collect rendered custom values files
  ansible.builtin.find:
    paths: "{{ ddns_updater_template_directory }}"
    patterns: "*.yaml"
  register: rendered_value_files

- name: Depoy Helm chart
  kubernetes.core.helm:
    name: "{{ ddns_updater_helm.release }}"
    chart_ref: "{{ ddns_updater_helm.chart }}"
    release_namespace: "{{ ddns_updater_chart.namespace }}"
    reuse_values: true
    values_files: "{{ rendered_value_files.files | map(attribute='path') | list }}"
    kubeconfig: "{{ ansible_nas.kubeconfig }}"
  delegate_to: manager1
  run_once: true
