# create values fro redis

image:
  repository: redis
  tag: 6.0.9
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

env:
  ALLOW_EMPTY_PASSWORD: "yes"
  REDIS_DISABLE_COMMANDS: "FLUSHDB,FLUSHALL"

persistance:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /dozer/docker/redis/data

networkPolicy:
  enabled: false

restartPolicy: UnlessStopped

replicaCount: 1
nameOverride: ""
fullnameOverride: ""