---
ansible_nas_user: "{{ ansible_nas.user }}"
ansible_nas_user_group: "{{ ansible_nas.user_group }}"
ansible_python_interpreter: "{{ ansible_nas.python_interpreter }}"
ansible_nas_email: "{{ ansible_nas.email }}"
container_count: "{{ ansible_nas.container_count }}"
default_container_name: "{{ ansible_nas.default_container_name }}"
default_container_image: "{{ ansible_nas.default_container_image }}"
default_container_command: "{{ ansible_nas.default_container_command }}"
ansible_nas_timezone: "{{ ansible_nas.timezone }}"
docker_home: "{{ ansible_nas.docker_home }}"
ansible_nas_domain: "{{ ansible_nas.domain }}"
ansible_nas_hostname: "{{ ansible_nas.hostname }}"
ansible_kubeconfig: "{{ ansible_nas.kubeconfig }}"