---
timemachine_data_directory: "{{ docker_home }}/timemachine"
timemachine_volume_size_limit: "0"
timemachine_password: "{{ lookup('password', 'TIMEMACHINE_PASSWORD') }}"
timemachine_share_name: Data
timemachine_log_level: error
timemachine_port: "10445"
