---

- name: Setup NAS with specific configurations
  hosts: all
  vars_files:
    - group_vars/all.yml
    - group_vars/influxdb.yml
    - group_vars/samba.yml
    - group_vars/joomla.yml
    - group_vars/openvpn.yml
    - group_vars/guacamole.yml
    - group_vars/krusader.yml
    - group_vars/timemachine.yml
    - group_vars/thelounge.yml
    - group_vars/wallabag.yml
    - group_vars/calibre.yml
    - group_vars/openhab.yml
    - group_vars/ubooquity.yml
    - group_vars/virtual_desktop.yml

  tasks:
    - name: Load environment variables from .env file
      community.general.read_env:
        path: "{{ playbook_dir }}/.env"

    - name: Set InfluxDB variables
      set_fact:
        influxdb_username: "{{ lookup('env', 'INFLUXDB_USERNAME') }}"
        influxdb_password: "{{ lookup('env', 'INFLUXDB_PASSWORD') }}"

    - name: Ensure all configurations are applied
      debug:
        msg: "Configurations applied successfully."

    - name: Debug - Show InfluxDB variables (for verification)
      debug:
        msg:
          - "InfluxDB Username: {{ influxdb_username }}"
          - "InfluxDB Password: {{ influxdb_password }}"
