replicaCount: 1

image:
  repository: qmcgaw/ddns-updater
  pullPolicy: IfNotPresent
  tag: "v2.7.1"

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

config:
  log_level: info
  update_period: 10m
  delay_start: 0s
  public_ip_fetchers:
    - opendns
    - google
  records:
    - provider: cloudflare
      domain: example.com
      host: "@"
      key: "<Your-Cloudflare-API-Key>"
      email: "<Your-Cloudflare-Email>"
      ttl: 300
      ip_version: ipv4
      proxied: false
