---
- name: Deploy to think-mini
  hosts: k3s_manager
  pre_tasks:
  roles:
    # - role: ddns_updater

- name: Deploy to think-mini
  hosts: k3s_workers
  pre_tasks:
  roles:
    # - role: ddns_updater

- name: Deploy
  hosts: managers, workers
  vars_files:
    - ../inventory/prod/sample-secrets.yml
  pre_tasks:
  roles:
    # - role: ../roles/ddns_updater
    - role: ../roles/caddy
