---
- name: Setup Docker Swarm
  hosts: all
  become: true
  tasks:
    - name: Initialize Docker Swarm on the first node
      shell: docker swarm init
      when: inventory_hostname == groups['all'][0]

    - name: Get Swarm join token
      shell: docker swarm join-token -q worker
      register: swarm_join_token
      when: inventory_hostname == groups['all'][0]

    - name: Join other nodes to the Swarm
      shell: "docker swarm join --token {{ hostvars[groups['all'][0]]['swarm_join_token'] }} {{ hostvars[groups['all'][0]]['ansible_host'] }}:2377"
      when: inventory_hostname != groups['all'][0]
      delegate_to: "{{ groups['all'][0] }}"
