---
- name: Setup k3s
  hosts: all
  become: true
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: Install k3s server on the first node
      shell: curl -sfL https://get.k3s.io | sh -
      when: inventory_hostname == groups['all'][0]

    - name: Get k3s join token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_join_token
      when: inventory_hostname == groups['all'][0]

    - name: Set k3s join token as fact
      set_fact:
        k3s_join_token: "{{ k3s_join_token.stdout }}"
      when: inventory_hostname == groups['all'][0]

    - name: Wait for k3s server to be ready
      wait_for:
        port: 6443
        host: "{{ hostvars[groups['all'][0]]['ansible_host'] }}"
        timeout: 300
      when: inventory_hostname != groups['all'][0]

    - name: Join other nodes to k3s server
      shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['all'][0]]['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars[groups['all'][0]]['k3s_join_token'] }} sh -"
      when: inventory_hostname != groups['all'][0]

    - name: Wait for k3s service to start
      systemd:
        name: k3s
        state: started
      when: inventory_hostname == groups['all'][0]

    - name: Wait for k3s-agent service to start
      systemd:
        name: k3s-agent
        state: started
      when: inventory_hostname != groups['all'][0]
