apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ddns_updater.fullname" . }}
  labels:
    app: {{ include "ddns_updater.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ddns_updater.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ddns_updater.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/ddns-updater/config.json
              subPath: config.json
          env:
            - name: CONFIG_FILE
              value: /etc/ddns-updater/config.json
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "ddns_updater.fullname" . }}
