apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddns-updater-pvc-{{ include "ddns_updater.uniqueSuffix" . }}
  labels:
    app: {{ include "ddns_updater.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
