---
# defaults file for roles/ddns_updater

# infrastructure
ddns_updater_data_directory: "{{ docker_home }}/ddns_updater"
ddns_updater_template_directory: "/tmp/ddns_updater"

ddns_updater_values:
  chart: "{{ helm.chart.ddns_updater }}"
  namespace: "ddns-updater"
  release: "ddns-updater"
  replicaCount: 1
  uniqueSuffix: "{{ ddns_updater_release }}"
  image:
    repository: qmcgaw/ddns-updater
    pullPolicy: IfNotPresent
    tag: v2.6.0

  service:
    type: ClusterIP
    port: 80

  config:
    log_level: info
    update_period: 10m
    delay_start: 0s
    public_ip_fetchers:
      - all
    public_ip_http_providers:
      - all
    records:
      - provider: "cloudflare"
        domain: "{{ lookup('env', 'DDNS_UPDATER_DOMAIN') }}"
        zone_identifier: "{{ lookup('env', 'DDNS_UPDATER_ZONE_IDENTIFIER') }}"
        host: "@"
        key: "{{ lookup('env', 'DDNS_UPDATER_KEY') }}"
        email: "{{ lookup('env', 'DDNS_UPDATER_EMAIL') }}"
        ttl: 300
        ip_version: ipv4
        proxied: true

  persistentVolume:
    reclaimPolicy: Retain
    hostPath: "{{ ddns_updater_data_directory }}"
    storage: 1Gi
    accessModes:
      - ReadWriteOnce
