apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
      containers:
        - name: ombi
          image: linuxserver/ombi
          ports:
            - containerPort: 3579
              hostPort: {{ .Values.network.port }}
          volumeMounts:
            - mountPath: /config
              name: config-volume
          env:
            - name: TZ
              value: {{ .Values.env.timezone }}
            - name: PUID
              value: {{ .Values.uid }}
            - name: PGID
              value: {{ .Values.gid }}
          resources:
            limits:
              memory: {{ .Values.specs.memory }}
          restartPolicy: Always
          securityContext:
            runAsUser: {{ .Values.uid }}
            runAsGroup: {{ .Values.gid }}
      volumes:
        - name: config-volume
          hostPath:
            path: {{ .Values.directories.configDirectory }}
