ombi:
  enabled: true
  availableExternally: true

directories:
  configDirectory: "/var/lib/ombi/config"

network:
  port: 8085
  hostname: "ombi"

uid: "0"
gid: "0"

specs:
  memory: "1Gi"

env:
  timezone: "UTC"

traefik:
  domain: "example.com"
  enableTls: true
  certresolver: "letsencrypt"
  middlewares: "authelia@docker"
