image:
  repository: redis
  tag: 6.0.9
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

env:
  ALLOW_EMPTY_PASSWORD: "yes"
  REDIS_DISABLE_COMMANDS: "FLUSHDB,FLUSHALL"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /dozer/docker/redis/data

networkPolicy:
  enabled: false

restartPolicy: Always

replicaCount: 1
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
