name: Release Charts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.7.0

      - name: Lint all Helm charts
        run: |
          for chart in $(find helm-charts -name Chart.yaml -exec dirname {} \;); do
            echo "Linting chart in $chart"
            helm lint $chart
          done